os: linux
language: java
dist: focal
jdk:
  - openjdk11

install: true

script: 
  - mvn --settings travis-settings.xml deploy site site-deploy -Dhttps.protocols=TLSv1.2 -D maven.wagon.http.ssl.insecure=true -D maven.wagon.http.ssl.allowall=true

after_success:
  - bash <(curl -s https://codecov.io/bash)
