name: Chimera CI/CD

on:
  push:
    branches:
      - master
      
env:
  SONATYPE_USERNAME: ${{secrets.SONATYPE_USERNAME}}
  SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
      - run: mvn install --settings ci-settings.xml --no-transfer-progress
