name: Chimera CI/CD

on:
  push:
    branches:
      - staging
      - stable

env:
  SONATYPE_USERNAME: ${{secrets.SONATYPE_USERNAME}}
  SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}
  
jobs:
  site:
    runs-on: ubuntu-20.04
    steps:
      - uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: mvn deploy site site-deploy -Dhttps.protocols=TLSv1.2 -D maven.wagon.http.ssl.insecure=true -D maven.wagon.http.ssl.allowall=true --settings ci-settings.xml --no-transfer-progress
      - run: bash <(curl -s https://codecov.io/bash)